### ISSUE TITLE
Investigar, documentar y seleccionar librerías disponibles para hacer OCR en el backend

### ISSUE THREAD

**Issue by damianfanaro** [IgrowkerTraining/i004-voltix-back#1]

**Comment by damianfanaro** [comment]
No perder mucho tiempo con esto. La idea es encontrar una librería con curva de aprendizaje fácil.
Les proprongo mirar: 
- PDFplumber + pytesseract
- easyocr
- ocrmypdf

OBJETIVO: Tomar una decisión sobre que lib o libs usar.

**Comment by darioduarte1** [comment]
El Reconocimiento Óptico de Caracteres (OCR) de Azure es una herramienta avanzada que permite extraer texto impreso y manuscrito de imágenes y documentos en múltiples idiomas. Forma parte de Azure AI Vision y se integra fácilmente en aplicaciones que requieren procesamiento de texto a partir de contenido visual.

Características principales:

Extracción de texto impreso y manuscrito: Capaz de identificar y extraer texto de diversos documentos e imágenes.

Soporte multilingüe: Compatible con más de 80 idiomas, incluyendo caracteres complejos. 
MICROSOFT LEARN

Detección de texto en imágenes y documentos: Procesa imágenes generales y documentos digitales o escaneados.

APIs síncronas y asíncronas: Ofrece APIs adaptadas a diferentes niveles de complejidad documental.

Integración con otros servicios de Azure: Permite construir soluciones más completas y robustas.

Beneficios:

Precisión y eficiencia: Utiliza algoritmos avanzados para garantizar una alta precisión en la extracción de texto.

Escalabilidad: Al ser un servicio en la nube, se adapta a diversas necesidades, desde pequeñas aplicaciones hasta grandes volúmenes de procesamiento.

Facilidad de uso: Proporciona APIs bien documentadas y fáciles de integrar.

Seguridad y cumplimiento: Cumple con los estándares de seguridad y privacidad de Azure.

Casos de uso:

Digitalización de documentos: Transforma documentos físicos en texto digital editable y buscable.

Análisis de contenido visual: Extrae información de imágenes para análisis de datos.

Automatización de procesos empresariales: Facilita tareas como facturación o gestión de inventarios.

Consideraciones:

Requisitos de entrada: Soporta formatos como JPEG, PNG, BMP, PDF y TIFF, con ciertas restricciones en tamaño y número de páginas. 
MICROSOFT LEARN

Calidad de la imagen: La precisión puede verse afectada por la calidad de la imagen; documentos de baja calidad pueden requerir preprocesamiento.

Chic@s para más información detallada, pueden consultar la [documentación oficial de Azure OCR](https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/overview-ocr).


por favor dicerme o que vos parece!

**Comment by kamelmat** [comment]
Acabo de terminar el intento de instalación de un downgrade de Tesseract a través  de homebrew y no funciona. Descarto esta opción y apoyo la de @darioduarte1 de tirar por Azure. 

El servicio de Azure Cognitive Services OCR no es completamente gratuito, pero ofrece un nivel gratuito con ciertas limitaciones que podrían ser suficientes para pruebas o proyectos pequeños.

Detalles sobre el nivel gratuito de Azure OCR:

Nivel gratuito de Azure Cognitive Services:
El nivel gratuito incluye un número limitado de solicitudes. Para la API de Computer Vision, en el nivel gratuito tienes:
500 transacciones gratuitas al mes para el servicio de OCR.
Estas solicitudes pueden ser suficientes si planeas hacer uso ocasional o pruebas del servicio.

Después del nivel gratuito:
Una vez que hayas agotado las 500 solicitudes gratuitas o si necesitas hacer más solicitudes, se te cobrará según las tarifas de Azure.

Los precios pueden variar dependiendo del servicio que utilices y el número de transacciones. Puedes consultar las tarifas actualizadas en el [portal de precios de Azure](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/computer-vision/).

**Comment by darioduarte1** [comment]
creo que para lanzar el MVP es la solucion mas adaptable a nosotros! el resto del equipo que se pronuncie y tiramos para adelante con azure o buscamos otro

**Comment by elmarqueze** [comment]
Se tomó la decisión de usar Azure.
Se movió la tarea a Done.

**Comment by ariellpcuba** [comment]
Un detalle, el despliegue de los servicios se va a realizar en AWS, esto nos llevaria a una solucion multicloud.
Pregunta, con cual suscripcion se va a realizar? a futuro no es viable en relacion de costos trabajar con dos nubes en caso de escalar.

Una alternativa seria: https://aws.amazon.com/textract/?did=ft_card&trk=ft_textract
