### ISSUE TITLE
Guardar los datos detectados en una factura en una base de datos NoSQL / sera con SQL (investigación)

### ISSUE THREAD

**Issue by damianfanaro** [IgrowkerTraining/i004-voltix-back#3]

**Comment by damianfanaro** [comment]
La siguiente tarea conlleva lo siguiente:

- [ ] Configurar una instancia gratuita en MongoDB Atlas (https://www.mongodb.com/es/lp/cloud/atlas/try7). Vamos a usar una base de datos orientada a documentos para almacenar información semi-estructurada. Por qué? Porque las facturas serán de distintas empresas que podrán información variable. Por lo tanto, no sería eficiente pensar en una tabla relacional.
- [ ] Crear al menos una colección que sea: `invoices` para almacenar los datos de todas las facturas.
- [ ] Construir un modelo inicial con los datos básicos de una factura: número de serie, empresa emisora, cliente o empresa receptora, fecha de emisión, fecha de vencimiento, importe, etc.

**Comment by NataliaIacono** [comment]
Se decidió en back que se utilizará un base relacional en este caso con PostgreSQL. El MVP tendrá la posibilidad de cargar un tipo de factura. Hablado con Damián.
