### ISSUE TITLE
POST /api/profile/change-password/: Permite al usuario cambiar su contraseña

### ISSUE THREAD

**Issue by NataliaIacono** [IgrowkerTraining/i004-voltix-back#41]

**Comment by NataliaIacono** [comment]
Implementar validación y confirmación de contraseña para mejorar la seguridad.

**Comment by darioduarte1** [comment]
ya subido el primero commit con la funcionalid de cambiar la password! 

ya funcional equipo! @NataliaIacono @ILMPI @denis9diaz @EIAHRJAY @kamelmat 

para lo mirarren en postman hacer el siguiente:

https://bug-free-space-halibut-5g4q5p7p57j73vrpp-8000.app.github.dev/api/auth/profile/change-password/

con el body:

{
    "old_password": "XXX",
    "new_password": "XXX"
}

y con Authorization Bearer Token >>> acess_token

voy empezar a investigar toda la parte de confirmacion de la seguridad en el cambio del password

**Comment by darioduarte1** [comment]
ya subido el commit con la funcionalid de cambiar la password y se enviar un email del backend para el user dicendo que su password fue cambiada!

ya funcional equipo! @NataliaIacono @ILMPI @denis9diaz @EIAHRJAY @kamelmat

para lo mirarren en postman hacer el siguiente:

https:///api/auth/profile/change-password/

con el body:

{
"old_password": "",
"new_password": ""
}

y con Authorization Bearer Token >>> acess_token

si el user registrado tiene un email valido, el mismo deberia recibir este contenido

Subject: Notificación de cambio de contraseña

Message:
Hola
Queremos informarte que tu contraseña ha sido cambiada exitosamente.
Si no realizaste este cambio, por favor contacta con nuestro equipo de soporte de inmediato.
Saludos,
El equipo de Voltix

LETS GO EQUIPO
