### ISSUE TITLE
Endpoint UserProfile

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i004-voltix-back#6]
Descripción:
Crear el endpoint que permita obtener y actualizar la información del perfil del usuario. Este endpoint debe estar protegido por autenticación y debe permitir al usuario acceder y actualizar sus datos personales (nombre, correo electrónico, etc.).

**Comment by kamelmat** [comment]
Naty, podés pasarlo a inprogress que estoy con ello. 
@NataliaIacono
