### ISSUE TITLE
Evaluar datos a cargar en la base ficticia de Mi LUZ, y definir que operaciones hacer para realizar las comparaciones.

### ISSUE THREAD

**Issue by NataliaIacono** [IgrowkerTraining/i004-voltix-back#66]

**Comment by ILMPI** [comment]
<img width="827" alt="Calcular_factura" src="https://github.com/user-attachments/assets/cc29e815-d0de-4f74-9969-da77dbe04678">

**Comment by ILMPI** [comment]
Flujo, como veo ahora:

1. Recibimos los datos de la factura
2. Calculamos para tener data para campos definidos y meter en nuestra tabla Invoices?
3. Comparamos con campos definidos+ datos aleatorios de la tabla MiLuzBase según filtro, y resultado metemos en la tabla Measurements

**Comment by ILMPI** [comment]
Queda esperar que se extraigan los datos con tesseract por ahora.
