### ISSUE TITLE
Investigar si podemos implementar Celery y Redis. Y cómo deberíamos hacerlo.

### ISSUE THREAD

**Issue by NataliaIacono** [IgrowkerTraining/i004-voltix-back#94]

**Comment by ILMPI** [comment]
Casi cada funcionalidad podría beneficiarse del uso de Celery y Redis para la ejecución de tareas en segundo plano. Aquí algunos ejemplos:

-     Autenticación:
    -         Caso de uso: Envío de correos electrónicos para confirmación o restablecimiento de contraseñas.
    -         Uso de Celery y Redis: Procesar estas tareas de manera asincrónica para mejorar el rendimiento.

-     Facturación (Invoices):
    -         Caso de uso: Generar facturas o realizar cálculos complejos.
    -         Uso de Celery y Redis: Colocar estas tareas en una cola para procesarlas sin afectar al usuario final.

-     Mediciones (Measurements)***:
    -         Caso de uso: Importar datos masivos o ejecutar análisis.
    -         Uso de Celery y Redis: Ejecutar estas operaciones en segundo plano.
 
-     Notificaciones***:
   -         Caso de uso: Enviar notificaciones masivas (SMS, correo, push).
   -         Uso de Celery y Redis: Procesar notificaciones en lotes para mayor eficiencia.

-     Tesseract (OCR):
    -         Caso de uso: Reconocer texto en imágenes.
    -         Uso de Celery y Redis: Ejecutar tareas pesadas de OCR de manera asincrónica.
 
-     Tareas Generales:
    -         Programar operaciones periódicas como copias de seguridad, limpieza de datos, o cálculos analíticos.

*** para ampliar funcionalidad y simular

**Comment by ILMPI** [comment]
Recursos:
    Documentación de Celery: https://docs.celeryproject.org
    Guía sobre Redis: https://redis.io/docs/
    Implementación en Django: https://docs.djangoproject.com/en/dev/howto/celery/

**Comment by ILMPI** [comment]
Como implementar:

1. Instalar + añadir a requirements.txt
2. Configurar
3. En cada módulo, definir tareas en un archivo tasks.py
4. Configurar para docker ----> Modificar docker-compose.yml para incluir Redis y Celery
5. * para tareas periodicas utilizarlo celery beat

**Comment by ILMPI** [comment]
**Implementación de Autenticación (Login)**
1. Objetivo:

Usar Celery y Redis para gestionar procesos asincrónicos durante la autenticación de usuarios (inicio de sesión). Esto puede incluir tareas como:

    Registro de intentos de inicio de sesión.
    Bloqueo de cuentas tras múltiples intentos fallidos.
    Generación de logs o auditoría.
    Validación de credenciales contra sistemas externos (como un servicio LDAP o API).

2. Flujo del Proceso

    Usuario Ingresa Credenciales:
        El usuario introduce su correo electrónico/usuario y contraseña en el formulario de inicio de sesión.
        Estos datos son enviados al servidor para su validación.

    Validación Inicial:
        El servidor verifica si las credenciales son correctas utilizando la base de datos local o externa.
        Si las credenciales son válidas:
            El usuario obtiene acceso a su cuenta.
            Se dispara una tarea de Celery para registrar el evento o generar logs.
        Si las credenciales son incorrectas:
            El intento fallido se registra y el usuario recibe una notificación.

    Tarea Asincrónica con Celery:
        Al validar correctamente, se ejecutan tareas en segundo plano como:
            Guardar los intentos exitosos o fallidos en un sistema de auditoría.
            Registrar la información de inicio de sesión (ubicación, IP, dispositivo) para alertas de seguridad.
        Redis actúa como broker para enviar estas tareas al trabajador de Celery.

    Bloqueo de Cuenta (Si Aplica):
        Si hay múltiples intentos fallidos consecutivos:
            Celery puede manejar un contador en Redis para verificar cuántos intentos incorrectos se realizaron.
            Si se supera un límite, se envía una señal para bloquear temporalmente la cuenta.

    Notificación (Opcional):
        Si se detecta un inicio de sesión sospechoso (nueva ubicación, dispositivo no reconocido), Celery puede disparar una tarea para enviar una notificación al usuario (correo o push).

3. Ventajas del Uso de Celery y Redis:

    Desempeño: El registro de logs, auditorías o notificaciones no ralentiza el proceso de inicio de sesión.
    Escalabilidad: Redis puede manejar múltiples tareas en cola para sistemas con gran cantidad de usuarios concurrentes.
    Flexibilidad: Se pueden añadir nuevas tareas fácilmente sin modificar el flujo principal.

4. Implementación del Flujo Paso a Paso

    Usuario envía credenciales → Servidor valida credenciales.
    Si las credenciales son correctas:
        Registro del evento exitoso o tareas adicionales (en segundo plano con Celery).
    Si las credenciales son incorrectas:
        Incremento del contador de intentos fallidos en Redis.
        Verificación del estado de la cuenta (bloqueada o activa).
    Redis envía las tareas al trabajador de Celery:
        Guardar logs.
        Generar reportes de auditoría.
        Enviar alertas en caso de actividad sospechosa.
    El usuario recibe una respuesta inmediata mientras las tareas se procesan en el fondo.

5. Recursos Recomendados:

    Auditoría y Seguridad en Django: https://docs.djangoproject.com/en/stable/topics/security/
    Celery y Tareas Distribuidas: https://docs.celeryproject.org
    Redis para Sistemas Escalables: https://redis.io/docs/

**Comment by ILMPI** [comment]
**Resumen y Plan de Procesamiento: PDF + OCR → JSON → Base de Datos**

Flujo

    Recepción del PDF:
        El archivo PDF se recibe a través de la API.
        La tarea de procesamiento se delega a Celery utilizando Redis como message broker.

    Cola de Tareas (Redis):
        Redis actúa como una cola de tareas.
        Los trabajadores de Celery procesan los PDFs en segundo plano.

    Procesamiento del PDF con Celery:

        Las tareas incluyen:
            Conversión del PDF a imágenes.
            Procesamiento de las imágenes.
            OCR para extraer texto.
            Transformación del texto a JSON.
            Guardado del JSON en la base de datos.

    Respuesta al Usuario:
        El usuario recibe una respuesta inmediata indicando que el procesamiento está en curso.
        Una vez completado, los resultados están disponibles en la base de datos.
